# Desc: 'Dev' docker compose file for local development of the gams-api.
# Starts-up required external services for gams-api, needed for testing
# and development like fedora6 and its dependent database.
# author: Sebastian Stoff

version: "3.7"

networks:
  default:
    name: gams-api-dev

services:

  relationalDB:
    image: postgres:15.3
    container_name: relationalDB
    hostname: relationalDB
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=gams
      - PGDATA=/var/lib/postgresql/data/pgdata
    # optional: persist postgres data via volume
    volumes:
      # needs additional wsl config to work if under wsl and bug occurs: https://stackoverflow.com/questions/65582382/wsl2-docker-linux-permission-issue-with-volumes
     - ${PWD}/docker/apps/postgres/postgres-data:/var/lib/postgresql/data

  facetSearch:
    container_name: facetSearch
    hostname: facetSearch
    image: solr:9.2.1
    ports:
      - "8983"
      - "8983:8983"
    command:
      # - mkdir /var/solr
      # - bash -c "chown -R 8983:8983 /var/solr && runuser -u solr -- solr-precreate default-core"
      - solr-precreate
      - gams

  triplestore:
    container_name: triplestore
    hostname: triplestore
    image: stain/jena-fuseki:4.8.0
    ports:
      - "3030:3030"
    environment:
      - "FUSEKI_DATASET_1=gams"
