
## default connection pool
# spring.datasource.hikari.connectionTimeout=20000
# spring.datasource.hikari.maximumPoolSize=5

spring:
  datasource:
    url: jdbc:postgresql://relationalDB:5432/gams
    username: admin
    password: admin
  jpa:
    hibernate:
      # set to create if you want to drop existing data on app startup
      # value "none" would require to initialize a schema via SQL va extra file
      ddl-auto: update
      properties:
        hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate.jdbc.lob.non_contextual_creation: true


  #####
  # Thymeleaf config
  # enables thymeleaf creation of hidden input fields for PUT and POST requests via html forms
  # https://stackoverflow.com/questions/38370011/thymeleaf-button-click-to-call-http-delete-method
  mvc:
    hiddenmethod:
      filter.enabled: "true"

  # sets the limit for multi-part files send via requests
  servlet:
    multipart:
      max-file-size: 10GB
      max-request-size: 10GB

  # spring profiles
  # profiles:
    # Override with  -Dspring-boot.run.profiles=<prod,stage,test>
    # active: ${SPRING_PROFILE:dev}

########
# Logging
# (handled in different profiles)
logging:
  file:
    name: ${LOG_FILE:log/app.log}
  level:
    org.zim.gamsapi: ${LOG_LEVEL:TRACE}
    # org.springframework.security: DEBUG

server:
  error:
    # includes stacktrace on error ( devtools will include it in dev)
    include-stacktrace: always


#####
# Custom properties for GAMS
#
gams:
  docker:
    # postgres
    relational-db: "relationalDB:5432"
    # fedora6
    repository-dns: "fcrepo:8080"
    #
    gateway-dns: "gateway:8080"
    #
    solr: "solr:8983"
    # fileserver
    apache: "apache:8080"
    # system triplestoree
    systemTriplestore: "localhost:3030"