spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gams
    username: admin
    password: admin

#####
# Custom properties for GAMS
#
gams:
  docker:
    # postgres
    relational-db: "localhost:5432"
    # from integration-api
    baseSearchUrl: ${BASE_SEARCH_URL:http://localhost:8983/solr/gams}
    triplestoreUrl: ${TRIPLESTORE_URL:http://localhost:3030/gams}