create table archival_record
(
    id                bigint                      not null,
    pid               varchar(255)                not null,
    timestamp         timestamp(6) with time zone not null,
    digital_object_id varchar(255)                not null,
    archival_status   varchar(255) not null default 'DRAFTED',
    external_id       varchar(255) not null,
    primary key (id)
);

create table datastream
(
    dsid              varchar(255) not null,
    file_path         varchar(255) not null,
    creator           varchar(255) not null,
    description       varchar(2000),
    md5_checksum      varchar(255) not null,
    rights            varchar(255) not null,
    sha512_checksum   varchar(255) not null,
    title             varchar(255) not null,
    created           timestamp(6) with time zone,
    created_by        varchar(255),
    mime_type         varchar(255) not null,
    modified          timestamp(6) with time zone,
    modified_by       varchar(255),
    size              bigint       not null,
    type              varchar(255),
    digital_object_id varchar(255) not null,
    archival_policy varchar(255) not null default 'DEFAULT',
    constraint DatastreamNameUniquePerObject primary key (digital_object_id, dsid)
);

create table datastream_content_deletion_failure
(
    id                bigint generated by default as identity,
    datastream_dsid   varchar(255) not null,
    digital_object_id varchar(255) not null,
    max_retries       integer,
    retry_count       integer,
    primary key (id)
);

create table datastream_lang
(
    datastream_digital_object_id varchar(255) not null,
    datastream_dsid              varchar(255) not null,
    datastream_lang              varchar(255)
);

create table datastream_tags
(
    datastream_digital_object_id varchar(255) not null,
    datastream_dsid              varchar(255) not null,
    datastream_tags              varchar(255)
);

create table datastream_content_restrictions
(
    datastream_digital_object_id varchar(255) not null,
    datastream_dsid              varchar(255) not null,
    datastream_content_restrictions varchar(255)
);

create table digital_object
(
    id                   varchar(255) not null,
    creator              varchar(255) not null,
    description          varchar(2000),
    rights               varchar(255) not null,
    title                varchar(255) not null,
    created              timestamp(6) with time zone,
    created_by           varchar(255),
    funder               varchar(255),
    main_resource        varchar(255),
    modified             timestamp(6) with time zone,
    modified_by          varchar(255),
    object_type          varchar(255),
    published            timestamp(6) with time zone,
    publisher            varchar(255) not null,
    project_project_abbr varchar(255) not null,
    ingested             boolean       not null default false,
    archive_state        varchar(255) default 'NOT_ARCHIVED'   not null,
    modified_after_creation boolean default false,
    primary key (id)
);

create table digital_object_tags
(
    digital_object_id   varchar(255) not null,
    digital_object_tags varchar(255)
);

create table dublin_core_entry
(
    id                bigint        not null,
    language          varchar(50),
    name              varchar(20)   not null,
    value             varchar(5000) not null,
    digital_object_id varchar(255)  not null,
    primary key (id)
);

create table integration_failure
(
    id                bigint generated by default as identity,
    digital_object_id varchar(255) not null,
    error_message     oid,
    failed_at         timestamp(6) with time zone,
    max_retries       integer,
    next_retry_at     timestamp(6) with time zone,
    operation         varchar(255) not null,
    project_abbr      varchar(255) not null,
    retry_count       integer,
    service_name      varchar(255) not null,
    status            varchar(255),
    primary key (id)
);

create table project
(
    project_abbr          varchar(10) not null,
    created               timestamp(6) with time zone,
    created_by            varchar(255),
    description           varchar(5000),
    modified              timestamp(6) with time zone,
    modified_by           varchar(255),
    title                 varchar(255),
    primary key (project_abbr)
);

create table submission_record
(
    digital_object_id               varchar(255) not null,
    bag_contact_mail                varchar(255) not null,
    bag_created_by                  varchar(255) not null,
    bag_external_description        varchar(255) not null,
    bag_payload_oxum                varchar(255) not null,
    bag_schema                      varchar(255) not null,
    bag_source                      varchar(255) not null,
    bag_tag_file_character_encoding varchar(255) not null,
    bag_version                     varchar(255) not null,
    bagging_date                    varchar(255) not null,
    gams_api_version                varchar(255) not null,
    primary key (digital_object_id)
);

create table web_deployment
(
    project_abbr varchar(10)                 not null,
    deployed_at  timestamp(6) with time zone not null,
    deployed_by  varchar(255)                not null,
    file_count   integer                     not null,
    total_size   bigint                      not null,
    primary key (project_abbr)
);

create index idx_dc_digital_object_id
    on dublin_core_entry (digital_object_id);

create index idx_dc_name
    on dublin_core_entry (name);

create index idx_dc_value
    on dublin_core_entry (value);

create index idx_dc_language
    on dublin_core_entry (language);

create sequence archival_record_seq start with 1 increment by 50;

create sequence dublin_core_entry_seq start with 1 increment by 50;

alter table if exists archival_record
    add constraint fk_archival_record_digital_object
    foreign key (digital_object_id)
    references digital_object;

alter table if exists datastream
    add constraint fk_datastream_digital_object
    foreign key (digital_object_id)
    references digital_object;

alter table if exists datastream_content_restrictions
    add constraint fk_ds_content_restrictions_datastream
    foreign key (datastream_digital_object_id, datastream_dsid)
    references datastream;

alter table if exists datastream_lang
    add constraint fk_ds_lang_datastream
    foreign key (datastream_digital_object_id, datastream_dsid)
    references datastream;

alter table if exists datastream_tags
    add constraint fk_ds_tags_datastream
    foreign key (datastream_digital_object_id, datastream_dsid)
    references datastream;

alter table if exists digital_object
    add constraint fk_digital_object_project
    foreign key (project_project_abbr)
    references project;

alter table if exists digital_object_tags
    add constraint fk_do_tags_digital_object
    foreign key (digital_object_id)
    references digital_object;

alter table if exists dublin_core_entry
    add constraint fk_dublin_core_entry_digital_object
    foreign key (digital_object_id)
    references digital_object;

alter table if exists submission_record
    add constraint fk_submission_record_digital_object
    foreign key (digital_object_id)
    references digital_object;

alter table if exists web_deployment
    add constraint fk_web_deployment_project
    foreign key (project_abbr)
    references project (project_abbr);