create table archival_record
(
    id                bigint                      not null,
    pid               varchar(255)                not null,
    timestamp         timestamp(6) with time zone not null,
    digital_object_id varchar(255)                not null,
    primary key (id)
);

create table datastream
(
    dsid              varchar(255) not null,
    bag_path          varchar(255) not null,
    creator           varchar(255) not null,
    description       varchar(2000),
    md5_checksum      varchar(255) not null,
    rights            varchar(255) not null,
    sha512_checksum   varchar(255) not null,
    title             varchar(255) not null,
    created           timestamp(6),
    created_by        varchar(255),
    mime_type         varchar(255) not null,
    modified          timestamp(6),
    modified_by       varchar(255),
    size              bigint       not null,
    type              varchar(255),
    digital_object_id varchar(255) not null,
    constraint DatastreamNameUniquePerObject primary key (digital_object_id, dsid)
);

create table datastream_content_deletion_failure
(
    id                bigint generated by default as identity,
    datastream_dsid   varchar(255) not null,
    digital_object_id varchar(255) not null,
    max_retries       integer,
    retry_count       integer,
    primary key (id)
);

create table datastream_lang
(
    datastream_digital_object_id varchar(255) not null,
    datastream_dsid              varchar(255) not null,
    datastream_lang              varchar(255)
);

create table datastream_tags
(
    datastream_digital_object_id varchar(255) not null,
    datastream_dsid              varchar(255) not null,
    datastream_tags              varchar(255)
);

create table digital_object
(
    id                   varchar(255) not null,
    creator              varchar(255) not null,
    description          varchar(2000),
    md5_checksum         varchar(255) not null,
    rights               varchar(255) not null,
    sha512_checksum      varchar(255) not null,
    title                varchar(255) not null,
    created              timestamp(6),
    created_by           varchar(255),
    funder               varchar(255),
    main_resource        varchar(255),
    modified             timestamp(6),
    modified_by          varchar(255),
    object_type          varchar(255),
    published            timestamp(6),
    publisher            varchar(255) not null,
    project_project_abbr varchar(255) not null,
    ingest_state         varchar(255) default 'INGESTED'      not null,
    archive_state        varchar(255) default 'NOT_ARCHIVED'   not null,
    primary key (id)
);

create table digital_object_tags
(
    digital_object_id   varchar(255) not null,
    digital_object_tags varchar(255)
);

create table dublin_core_entry
(
    id                bigint        not null,
    language          varchar(50),
    name              varchar(20)   not null,
    value             varchar(5000) not null,
    digital_object_id varchar(255)  not null,
    primary key (id)
);

create table integration_failure
(
    id                bigint generated by default as identity,
    digital_object_id varchar(255) not null,
    error_message     oid,
    failed_at         timestamp(6),
    max_retries       integer,
    next_retry_at     timestamp(6),
    operation         varchar(255) not null,
    project_abbr      varchar(255) not null,
    retry_count       integer,
    service_name      varchar(255) not null,
    status            varchar(255),
    primary key (id)
);

create table project
(
    project_abbr          varchar(10) not null,
    content_last_modified timestamp(6),
    created               timestamp(6),
    created_by            varchar(255),
    description           varchar(5000),
    modified              timestamp(6),
    modified_by           varchar(255),
    title                 varchar(255),
    primary key (project_abbr)
);

create table submission_record
(
    digital_object_id               varchar(255) not null,
    bag_contact_mail                varchar(255) not null,
    bag_created_by                  varchar(255) not null,
    bag_external_description        varchar(255) not null,
    bag_payload_oxum                varchar(255) not null,
    bag_schema                      varchar(255) not null,
    bag_source                      varchar(255) not null,
    bag_tag_file_character_encoding varchar(255) not null,
    bag_version                     varchar(255) not null,
    bagging_date                    varchar(255) not null,
    gams_api_version                varchar(255) not null,
    primary key (digital_object_id)
);

create index idx_dc_digital_object_id
    on dublin_core_entry (digital_object_id);

create index idx_dc_name
    on dublin_core_entry (name);

create index idx_dc_value
    on dublin_core_entry (value);

create index idx_dc_language
    on dublin_core_entry (language);

create sequence archival_record_seq start with 1 increment by 50;

create sequence dublin_core_entry_seq start with 1 increment by 50;

alter table if exists archival_record
    add constraint FKbw4488rovwyth14g8cw5bt043
    foreign key (digital_object_id)
    references digital_object;

alter table if exists datastream
    add constraint FKg3kmj5h5ksplr9o7fr8usynmg
    foreign key (digital_object_id)
    references digital_object;

alter table if exists datastream_content_restrictions
    add constraint FKklhxyijulpegn3vvhe40f4pxv
    foreign key (datastream_digital_object_id, datastream_dsid)
    references datastream;

alter table if exists datastream_lang
    add constraint FKicsafqksm6xlq7q1yv3xgfom2
    foreign key (datastream_digital_object_id, datastream_dsid)
    references datastream;

alter table if exists datastream_tags
    add constraint FKcd9cg0efijgen3qlkpqxl82g5
    foreign key (datastream_digital_object_id, datastream_dsid)
    references datastream;

alter table if exists digital_object
    add constraint FKiscu1vj93tlk36fmmn42tifbx
    foreign key (project_project_abbr)
    references project;

alter table if exists digital_object_tags
    add constraint FKbckjsksr0o3ekojbl1t9eanl9
    foreign key (digital_object_id)
    references digital_object;

alter table if exists dublin_core_entry
    add constraint FKsvcn1qeh9v6k9kyqxwjtqdyap
    foreign key (digital_object_id)
    references digital_object;

alter table if exists submission_record
    add constraint FKc6deyb28usv7ceeidrmjjh4u5
    foreign key (digital_object_id)
    references digital_object;